version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/digits_db
    volumes:
      - ./webapp:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digits_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./webapp/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: